version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "05:00"
    timezone: UTC
- package-ecosystem: github-actions
  directory: /.github/workflows
  schedule:
    interval: daily
    time: "05:00"
    timezone: UTC
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
    time: "05:00"
    timezone: UTC
- package-ecosystem: terraform
  directory: __testdata__
  schedule:
    interval: daily
    time: "05:00"
    timezone: UTC
