name: domi Build, Push, and Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'

      - name: Build domi Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o bin/domi github.com/devops-kung-fu/domi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/devops-kung-fu/domi:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure .kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name domi-test
          kubectl get svc

      - name: Helm Install
        run: helm install domi ./domi-chart

      - name: domi URL
        run: |
          export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services domi)
          export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
          echo http://$NODE_IP:$NODE_PORT