name: Go Quality Checks
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Setup Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.23.0/conftest_0.23.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.23.0_Linux_x86_64.tar.gz
          ls
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get -u github.com/fzipp/gocyclo/cmd/gocyclo
      - name: Tests
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
      - name: CodeCov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: go build
      - name: Vet
        run: go vet -v
      - name: Lint
        run: golint ./...
      - name: gocyclo
        run: gocyclo .
        